# PI Planning - SAFe ART Event Workflow
name: pi-planning
description: "Facilitate the 2-day PI Planning event for ART alignment - the heartbeat of the Agile Release Train"
author: "BMad Method - SAFe"

# Critical variables from config
config_source: "{project-root}/_bmad-safe/bmm-safe/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad-safe/bmm-safe/workflows/4-implementation/pi-planning"
instructions: "{installed_path}/instructions.md"
template_pi_objectives: "{project-root}/_bmad-safe/bmm-safe/templates/safe/pi-objectives-template.md"
template_roam: "{project-root}/_bmad-safe/bmm-safe/templates/safe/roam-risk-template.md"
checklist_prep: "{project-root}/_bmad-safe/bmm-safe/checklists/pi-planning-prep.md"

# Variables and inputs
variables:
  project_context: "**/project-context.md"
  project_name: "{config_source}:project_name"
  
  # PI Planning artifacts
  product_vision: "{planning_artifacts}/*vision*.md"
  product_roadmap: "{planning_artifacts}/*roadmap*.md"
  top_features: "{planning_artifacts}/*feature*.md"
  architecture_vision: "{planning_artifacts}/*architecture*.md"

# Smart input file references
input_file_patterns:
  features:
    description: "All features prioritized by WSJF"
    whole: "{planning_artifacts}/*feature*.md"
    load_strategy: "FULL_LOAD"
  epics:
    description: "All epics from portfolio"
    whole: "{planning_artifacts}/*epic*.md"
    load_strategy: "FULL_LOAD"

# Output configuration
default_output_file: "{implementation_artifacts}/pi-objectives.md"

# Workflow mode
workflow:
  type: dual-mode
  modes:
    - Create
    - Facilitate

standalone: true

# Beads integration (additive)
beads:
  enabled: true
  safe_level: "feature"
  parent_level: "capability"
  on_start: "bd create 'PI: {{pi_name}}'"
  on_feature_commit: "bd create 'Feature: {{feature_name}}' --parent {{capability_bead_id}}"
  on_objective_commit: "bd note {{pi_bead_id}} 'PI Objective: {{objective_name}}'"
  on_complete: "bd done {{pi_bead_id}}"
