# System Demo - PI System Demo Event
name: system-demo
description: "Facilitate PI System Demo at the end of each PI to showcase integrated work from all teams"
author: "BMad Method - SAFe"

# Critical variables from config
config_source: "{project-root}/_bmad-safe/bmm-safe/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad-safe/bmm-safe/workflows/4-implementation/system-demo"
instructions: "{installed_path}/instructions.md"

# Variables and inputs
variables:
  project_context: "**/project-context.md"
  project_name: "{config_source}:project_name"
  
  # System Demo inputs
  pi_objectives: "{implementation_artifacts}/*pi-objectives*.md"
  completed_features: "{planning_artifacts}/*feature*.md"
  sprint_status: "{implementation_artifacts}/sprint-status.yaml"

# Smart input file references
input_file_patterns:
  features:
    description: "Completed features to demo"
    whole: "{planning_artifacts}/*feature*.md"
    load_strategy: "FULL_LOAD"
  stories:
    description: "Completed stories this PI"
    whole: "{implementation_artifacts}/*story*.md"
    load_strategy: "SCAN_HEADERS"

# Output configuration
default_output_file: "{implementation_artifacts}/system-demo-notes.md"

# Workflow mode
workflow:
  type: single-mode
  mode: Facilitate

standalone: true
