# Team Backlog Management - Prioritize and Manage Team Backlog
name: team-backlog
description: "Manage and prioritize the Team Backlog with WSJF and capacity-based planning"
author: "BMad Method - SAFe"

# Critical variables from config
config_source: "{project-root}/_bmad-safe/bmm-safe/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad-safe/bmm-safe/workflows/4-implementation/team-backlog"
instructions: "{installed_path}/instructions.md"
template_story: "{project-root}/_bmad-safe/bmm-safe/templates/safe/story-template.md"
template_wsjf: "{project-root}/_bmad-safe/bmm-safe/templates/safe/wsjf-calculator.md"
task_wsjf: "{project-root}/_bmad-safe/bmm-safe/tasks/apply-wsjf.md"

# Variables and inputs
variables:
  project_context: "**/project-context.md"
  project_name: "{config_source}:project_name"
  
  # Backlog inputs
  pi_objectives: "{implementation_artifacts}/*pi-objectives*.md"
  features: "{planning_artifacts}/*feature*.md"
  existing_stories: "{implementation_artifacts}/*story*.md"

# Smart input file references
input_file_patterns:
  features:
    description: "Features from ART backlog"
    whole: "{planning_artifacts}/*feature*.md"
    load_strategy: "SCAN_HEADERS"
  stories:
    description: "Existing stories in backlog"
    whole: "{implementation_artifacts}/*story*.md"
    load_strategy: "SCAN_HEADERS"

# Output configuration
default_output_file: "{implementation_artifacts}/team-backlog.md"

# Workflow mode
workflow:
  type: single-mode
  mode: Create

standalone: true
